import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { rubik } from "./fonts/fonts";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "Julia Voronina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang }
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  // console.log(lang)
  return (
    <html lang={lang} dir={lang === "he" ? "rtl" : "ltr"}>
      <body className={rubik.className}     >
        <Navbar lang={lang} />
        <main>
          {children}
        </main>
        <Footer lang={lang}/>
      </body>
    </html>
  );
}
