import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang }
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  // console.log(lang)
  return (
    <html lang={lang}>
      <body      >
        <Navbar lang={lang}/>
        {children}
      </body>
    </html>
  );
}
